### ISSUE TITLE
subordinate charms should have a limit in metadata

### ISSUE THREAD

**Issue by lucabello** [juju/juju#18665]
### Problem description

Customers and users frequently face issues with subordinate charms because Juju does not prevent:
1. relating a subordinate charm to more than one principal on the same vm
2. relating multiple subordinate applications (of the same charm) to the same principal

### Desired behaviour

It would be handy if charm's metadata had limits similar to relation limits for this use case.

For example:
```yaml
# charmcraft.yaml
subordinate: true
subordinate-limits:
  max-amount-of-principals: 1
  max-amount-of-subordinates: 1
```
