### ISSUE TITLE
Juju secret label not getting updated across relation

### ISSUE THREAD

**Issue by phvalguima** [juju/juju#18733]
## Environment

* juju: `3.6-beta2-genericlinux-amd64`
* ops: `ops-2.16.1.dist-info`

## Description

On secrets established across relations, I am noticing the following behavior, Juju is not setting the secret label on the receiving side of the relation.

When I look to the juju context within the secret-changed, I discover:
```
JUJU_SECRET_ID=secret:cuc9pu6jph339u5qjl30
JUJU_SECRET_LABEL=
```

When I look at my secret in juju, I get:
```
ubuntu@ip-172-31-71-246:~$ juju show-secret --reveal cuc9pu6jph339u5qjl30         
cuc9pu6jph339u5qjl30:                                                             
  revision: 2                                                                     
  checksum: 74c6cdf782c72c0ec5596c900f6dd523038b3d3e34bcba071cf94fdce35b3790      
  owner: main                                                                     
  label: main:app:s3-secret-key  # <<<<--------------------------------- label set correctly in the show-secret
  created: 2025-01-28T09:02:00Z                                                   
  updated: 2025-01-28T09:05:40Z                                                   
  content:                                                                        
    s3-secret-key: qbGklDUBXB7I5uuDgD5441POsKw4avG9fuArOTST                       
  access:                                                                         
  - target: application-failover                                                  
    scope: relation-failover.peer-cluster#main.peer-cluster-orchestrator          
    role: view                                                                    
  - target: application-opensearch                                                
    scope: relation-opensearch.peer-cluster#main.peer-cluster-orchestrator        
    role: view                                                                    
```

But, when running the event within the ops framework, I get:
```
2025-01-28 09:19:29,791 INFO     Secret secret:cuc9pu6jph339u5qjl30 has no label, ignoring it.                       
> /var/lib/juju/agents/unit-failover-1/charm/lib/charms/opensearch/v0/opensearch_backups.py(432)_on_secret_changed() 
-> if not event.secret.label or S3_CREDENTIALS not in event.secret.label:                                            
(Pdb) p event.secret.label                                                                                           
None                                                                                                                 
```

### Juju version

3.6-beta2

### Expected behaviour

To have `JUJU_SECRET_LABEL` set in both sides of the secret-changed.

### Reproduce / Test

Deploy:
```
juju deploy --channel=2/edge opensearch main
juju deploy --channel=2/edge opensearch failover
juju deploy --channel=latest/stable self-signed-certificates
juju deploy --channel=latest/stable s3-integrator
```

Then, relate:
```
juju relate main self-signed-certificates
juju relate failover self-signed-certificates
juju relate main s3-integrator
juju relate main:peer-cluster-orchestrator failover:peer-cluster
```

Once the cluster settles, do a `secret-set` on main's debug-hooks on the secret with label: `main:app:s3-secret-key`

That will trigger a `secret-changed` in both main/0 and failover/0.

In main/0, I can see:
```
root@juju-0e39a9-5:/var/lib/juju/agents/unit-main-0/charm# env | grep SECRET
JUJU_SECRET_ID=secret:cuc9pu6jph339u5qjl30                                  
JUJU_SECRET_LABEL=main:app:s3-secret-key                                    
```

In failover/0, I see:
```
root@juju-0e39a9-3:/var/lib/juju/agents/unit-failover-1/charm# env | grep SECRET 
JUJU_SECRET_ID=secret:cuc9pu6jph339u5qjl30                                       
JUJU_SECRET_LABEL=                                                               
```
