### ISSUE TITLE
Deploying a bundle on `arm64` prints `amd64` to stdout

### ISSUE THREAD

**Issue by sed-i** [juju/juju#19039]
### Description

When I deploy a bundle yaml file which has constraints to arm64, bundle deployment goes fine and everything is great, but the messages juju prints to stdout seem to give the wrong idea, incorrectly indicating `amd64` in some places:

```
$ juju deploy ./tests/manual/smoke/arm64.yaml 
Located charm "ubuntu" in charm-hub, channel latest/stable
Located charm "ubuntu" in charm-hub, channel latest/stable
Located charm "ubuntu" in charm-hub, channel latest/stable
Executing changes:
- upload charm /home/sidekick/grafana-agent-operator/grafana-agent_ubuntu@20.04-arm64.charm for base ubuntu@20.04/stable with architecture=amd64
- deploy application ga20 on ubuntu@20.04/stable
- upload charm /home/sidekick/grafana-agent-operator/grafana-agent_ubuntu@22.04-arm64.charm for base ubuntu@22.04/stable with architecture=amd64
- deploy application ga22 on ubuntu@22.04/stable
- upload charm /home/sidekick/grafana-agent-operator/grafana-agent_ubuntu@24.04-arm64.charm for base ubuntu@24.04/stable with architecture=amd64
- deploy application ga24 on ubuntu@24.04/stable
- upload charm ubuntu from charm-hub for base ubuntu@20.04/stable with revision 25 with architecture=arm64
- deploy application ub20 from charm-hub on ubuntu@20.04/stable with latest/stable using ubuntu
- upload charm ubuntu from charm-hub for base ubuntu@22.04/stable with revision 25 with architecture=arm64
- deploy application ub22 from charm-hub on ubuntu@22.04/stable with latest/stable using ubuntu
- upload charm ubuntu from charm-hub for base ubuntu@24.04/stable with revision 25 with architecture=arm64
- deploy application ub24 from charm-hub on ubuntu@24.04/stable with latest/stable using ubuntu
- add new machine 0 (bundle machine 1)
- add new machine 1 (bundle machine 2)
- add new machine 2 (bundle machine 3)
- add relation ga20:juju-info - ub20:juju-info
- add relation ga22:juju-info - ub22:juju-info
- add relation ga24:juju-info - ub24:juju-info
- add unit ub20/0 to new machine 0
- add unit ub22/0 to new machine 1
- add unit ub24/0 to new machine 2
Deploy of bundle completed.
```

Note how it says `upload charm ... grafana-agent_ubuntu@20.04-arm64.charm for base ubuntu@20.04/stable with architecture=amd64`.

### Juju version

3.6.2

### Cloud

LXD

### Expected behaviour

The message should say arm64 instead of amd64.

### Reproduce / Test

Deploy the following bundle on an arm64:

```yaml
default-base: ubuntu@24.04/stable
applications:
  ga20:
    charm: ../../../grafana-agent_ubuntu@20.04-arm64.charm
    base: ubuntu@20.04/stable
  ga22:
    charm: ../../../grafana-agent_ubuntu@22.04-arm64.charm
    base: ubuntu@22.04/stable
  ga24:
    charm: ../../../grafana-agent_ubuntu@24.04-arm64.charm
    base: ubuntu@24.04/stable
  ub20:
    charm: ubuntu
    channel: latest/stable
    revision: 25
    base: ubuntu@20.04/stable
    num_units: 1
    to:
    - "1"
    constraints: arch=arm64
  ub22:
    charm: ubuntu
    channel: latest/stable
    revision: 25
    base: ubuntu@22.04/stable
    num_units: 1
    to:
    - "2"
    constraints: arch=arm64
  ub24:
    charm: ubuntu
    channel: latest/stable
    revision: 25
    base: ubuntu@24.04/stable
    num_units: 1
    to:
    - "3"
    constraints: arch=arm64
machines:
  "1":
    constraints: arch=arm64
    base: ubuntu@20.04/stable
  "2":
    constraints: arch=arm64
    base: ubuntu@22.04/stable
  "3":
    constraints: arch=arm64
    base: ubuntu@24.04/stable
relations:
- - ga20:juju-info
  - ub20:juju-info
- - ga22:juju-info
  - ub22:juju-info
- - ga24:juju-info
  - ub24:juju-info
```

### Notes & References

Encountered while working on https://github.com/canonical/grafana-agent-operator/pull/262.
