### ISSUE TITLE
juju ssh or scp fails immediately if a model is not known to the client

### ISSUE THREAD

**Issue by nobuto-m** [juju/juju#19112]
### Description

When a model was created by somebody else or some other tools such as Terraform Juju provider than Juju CLI, `juju ssh -m mymodel-1` or `juju scp -m mymodel-1` fails.

How to reproduce:

1. juju bootstrap localhost localhost
2. juju add-model mymodel-1
3. juju add-model mymodel-2
4. edit `~/.local/share/juju/models.yaml` by hand and remove mymodel-1. This simulates a behavior where the mymodel-1 was created by somebody else (the controller and the other client know about the model, but this client doesn't know about the model yet)
5. run `juju ssh -m mymodel-1 foo/0`

Then, it returns an error:
`ERROR model localhost:admin/mymodel-1 not found`

[~/.local/share/juju/models.yaml]
```
controllers:
  localhost:
    models:
      admin/controller:
        uuid: 61ce41c7-e568-44d0-880e-44b0046c4e7b
        type: iaas
        branch: ""
      admin/mymodel-1:
        uuid: fc61041f-7a03-4c60-81a3-b800daafe47e
        type: iaas
        branch: ""
      admin/mymodel-2:
        uuid: b03e7bc9-7106-4cee-873a-7f46d720221a
        type: iaas
        branch: ""
    current-model: admin/mymodel-2
```

### Juju version

3.6.3

### Cloud

LXD, Kubernetes

### Expected behaviour

juju ssh or scp succeeds.

### Reproduce / Test

As above.

### Notes & References

As soon as the client talks to the controller by `juju models` for example, ~/.local/share/juju/models.yaml will have the missed models, and juju ssh or scp succeeds. In the meantime, other commands, juju exec or run doesn't have this issue.

This was found in:
https://bugs.launchpad.net/snap-openstack/+bug/2100739
