### ISSUE TITLE
Kubernetes Resource Requests in charmcraft.yaml

### ISSUE THREAD

**Issue by alexdlukens** [juju/juju#19193]
### Problem description

Kubernetes assigns pods to nodes based on resource availability. Currently, the resource requests are only set by Juju when performing juju deploy with constraints. E.g. `juju deploy charm-1 --constraints="cores=1 mem=2G"`

per the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/):

When you specify the resource request for containers in a Pod, the [kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) uses this information to decide which node to place the Pod on.

### Desired behaviour

Propose to enable defining default [kubernetes resource requests](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) in charmcraft.yaml such that charm developers may define their own reasonable default values. E.g. have a default-requests field inside containers [field in charmcraft.yaml](https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/files/charmcraft-yaml-file/#containers)

Extending the existing example:

```yaml
containers:
  super-app:
    resource: super-app-image
    mounts:
    - storage: logs
      location: /logs
    default-requests:
      cpu: "500m"
      memory: "1024Mi" 
```
This would define the resource requests used by the charm unless overridden during juju deploy by constraints.

Note that limits could also be configured, although I see this as less useful to define by the charm developer

### Notes & References

I have raised this issue on the charmcraft repository here: https://github.com/canonical/charmcraft/issues/2211, but they mention this would require effort by the juju team as well.
