### ISSUE TITLE
juju ssh initiates TCP SYN on all ip addresses of machine

### ISSUE THREAD

**Issue by selcem-artan** [juju/juju#19881]
### Description

When juju ssh <machine-id> is run, juju client initiates a TCP SYN request to all ip addresses of machine consequtively until it succeeds. The order of IP addresses from "juju show machine <ID>" does not match to the order of outgoing TCP SYN requests. So, would it be possible to change order? Because juju client has no access to all these network spaces and ssh request is being blocked by firewall.

```
  "8":
    juju-status:
      current: started
      since: 05 May 2025 17:48:32Z
      version: 3.6.4
    hostname: oshci07-nue5
    dns-name: 10.250.136.6
    ip-addresses:
    - 10.250.136.6
    - 10.250.138.14
    - 10.250.139.15
    - 10.250.140.105
    - 10.250.141.6
    - 10.250.142.6
    - 10.250.143.5
```
 

![Image](https://github.com/user-attachments/assets/edea2f71-5537-42e8-ae99-fffe9afcd82a)

### Juju version

3.6.5

### Expected behaviour

From juju show-machine output, it is expected ssh to be run to same list of IPs in given order from command output.

### Reproduce / Test

Install juju 3.6.5 and bootstrap controller and add a machine with multiple network addresses from different network spaces. Run "juju ssh <machine-ID>"  and check with tcpdump for outgoing TCP SYN requests
