### ISSUE TITLE
use of `ch:` required for charm value when re-deploying a bundle

### ISSUE THREAD

**Issue by baycarbone** [juju/juju#20011]
### Description

When deploying the [logrotated](https://charmhub.io/logrotated) charm using a ubuntu@22.04 base through a bundle, the initial deployment will succeed but subsequent deploys of the bundle will fail.

Example bundle:
```
default-base: ubuntu@22.04/stable
applications:
  logrotated:
    charm: logrotated
    channel: latest/stable
```

Initial deployment
```
$ juju deploy ./test-bundle.yaml
Located charm "logrotated" in charm-hub, channel latest/stable
Executing changes:
- upload charm logrotated from charm-hub for base ubuntu@22.04/stable from channel latest/stable with architecture=amd64
- deploy application logrotated from charm-hub on ubuntu@22.04/stable with latest/stable
Deploy of bundle completed.
```

Re-deploy
```
$ juju deploy ./test-bundle.yaml
Executing changes:
- upgrade logrotated from charm-hub using charm logrotated for base ubuntu@22.04/stable from channel latest/stable
ERROR cannot deploy bundle: unexpected charm "logrotated", charm not found for application "logrotated"
```

However, if the charm value is preceded with `ch:`, then the issue on re-deployment does not occur:
```
default-base: ubuntu@22.04/stable
applications:
  logrotated:
    charm: ch:logrotated
    channel: latest/stable
```

Re-deploy
```
$ juju deploy ./test-bundle.yaml
Located charm "logrotated" in charm-hub, channel latest/stable
Executing changes:
- upload charm logrotated from charm-hub for base ubuntu@22.04/stable from channel latest/stable with architecture=amd64
- upgrade logrotated from charm-hub using charm logrotated for base ubuntu@22.04/stable from channel latest/stable
Deploy of bundle completed.
```

### Juju version

3.6.5

### Cloud

MAAS

### Expected behaviour

When not specifying the charmhub prefix, the re-deploy of the bundle should still succeed.

### Reproduce / Test

Failing bundle:
```
default-base: ubuntu@22.04/stable
applications:
  logrotated:
    charm: logrotated
    channel: latest/stable
```

Working bundle:
```
default-base: ubuntu@22.04/stable
applications:
  logrotated:
    charm: ch:logrotated
    channel: latest/stable
```

### Notes & References
Colleagues have mentioned hitting this issue with other charms like [hardware-observer](https://charmhub.io/hardware-observer)

Discusion on Matrix: https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$KVpOW62T51_4lg8jUgQHLgZA8URry7ssQ5pzzPs8glc?via=ubuntu.com&via=matrix.org&via=xentonix.net
