### ISSUE TITLE
azure provider does not appear to be opening ports

### ISSUE THREAD

**Issue by bac** [juju/juju#3999]
Using a hand-built juju 1.26-alpha3-wily-amd64 from 40b2cae9245b I am able to bootstrap onto Azure and deploy the juju-gui.  The charm opens and exposes ports 80 and 443.  `juju status` shows them to be open. (See below)

The steps I followed are:
```
juju bootstrap --upload-tools
cd ~/git/juju-gui-charm
make deploy
```

Attempting to hit the public IP address in a browser yields no response.  Using nmap to scan shows only port 22 open:

```
$ nmap -Pn 138.91.252.121

Starting Nmap 6.47 ( http://nmap.org ) at 2015-12-18 12:33 AST
Nmap scan report for 138.91.252.121
Host is up (0.11s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
22/tcp open  ssh
```

`juju status` output:
```
  juju-gui:
    charm: local:trusty/juju-gui-0
    exposed: true
    service-status:
      current: unknown
      since: 18 Dec 2015 11:38:40-04:00
    units:
      juju-gui/0:
        workload-status:
          current: unknown
          since: 18 Dec 2015 11:38:40-04:00
        agent-status:
          current: idle
          since: 18 Dec 2015 12:30:30-04:00
          version: 1.26-alpha3.1
        agent-state: started
        agent-version: 1.26-alpha3.1
        machine: "1"
        open-ports:
        - 80/tcp
        - 443/tcp
        public-address: 138.91.252.121
```
