### ISSUE TITLE
Rackspace cloud "unknown config field domain-name"

### ISSUE THREAD

**Issue by wurde** [juju/juju#5794]
ERROR unknown config field "domain-name"

Can't seem to bootstrap the rackspace cloud. The "domain-name" field is filled out by the `juju add-credential rackspace` command, so it's not some random field. 

On a side note, the list of endpoints for rackspace regions seems to be lacking. What's with the empty brackets?

```
defined: public
type: rackspace
auth-types: [access-key, userpass]
endpoint: https://identity.api.rackspacecloud.com/v2.0
regions:
  dfw: {}
  ord: {}
  iad: {}
  lon:
    endpoint: https://lon.identity.api.rackspacecloud.com/v2.0
  syd: {}
  hkg: {}
```
