### ISSUE TITLE
Declaring repositories into a yaml file

### ISSUE THREAD

**Issue by sebas5384** [juju/juju#87]
Every time I have to deploy or upgrade a charm, that is in a local directory for example, I have to re declare every time the location.

**Today:**
```bash
juju deploy --repository ~/charms local:precise/drupal
```

**Suggestion:**
```yaml
local_project:
  type: local
  repositories:
    - name: local
      path: ~/charms
    - name: my_repo
      path: git@github.com:sebas5384/juju-charms
```
```bash
juju deploy local:precise/drupal
```
The repo thing, is not that important, since I have a repo for each charm, so, I can just clone/pull the charm in the local directory.

**Other idea:**
Having a ~/.juju/repositories.yaml where global repositories can be used in every environment.
